export const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/magnetite.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/acabou_o_chorare.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/nirvana.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/both__sides.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Thriller",
    category: 1,
    price: 120.95,
    img: "./src/assets/img/thriller.jpeg",
    band: "Michael Jackson",
    year: 1982,
    id: 4,
  },
  {
    title: "Songs in the Key of Life",
    category: 1,
    price: 128.90,
    img: "./src/assets/img/StevieWonder.jpg",
    band: "Stevie Wonder",
    year: 1976,
    id: 5,
  },
  {
    title: "Children of the World",
    category: 1,
    price: 76.00,
    img: "./src/assets/img/Bee_Gees.jpg",
    band: "Bee Gees",
    year: 1976,
    id: 6,
  },
  {
    title: "Yellow Submarine",
    category: 1,
    price: 128.90,
    img: "./src/assets/img/yellow__submarine.jpeg",
    band: "Beatles",
    year: 1968,
    id: 7,
  },
  {
    title: "Like a Virgin",
    category: 1,
    price: 42.41,
    img: "./src/assets/img/madonna.webp",
    band: "Madonna",
    year: 1984,
    id: 7,
  },
];

